version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - UPDATES_CHANNEL=${UPDATES_CHANNEL}
      - API_ID=${}
