version: "3.10"
services:
  worker:
    build: "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest"
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - OWNER_ID=${OWNER_ID}
      - DATABASE_URL=${DATABASE_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - UPDATES_CHANNEL=${UPDATES_CHANNEL}
      - PRESET=${PRESET}
